### ISSUE TITLE
Allow likes on articles

### ISSUE THREAD

**Issue by salahusama** [mai-youth/website-be#9]
This shouldn't be too difficult, but it might be useful to know what articles are most read and liked. Liked / Upvoted / Clapped, etc

Liking articles without logging in may be an issue because you don't want people to like an article multiple times.

A solution to this may be to set a unique id for a machine the first time the page loads, then checking if they liked the page before or not.

A simpler solution may be to store a list of liked article ids in `localStorage` and not allow them to like an article twice. If the article id is in that list, highlight the like button, otherwise don't highlight it.

Every view can count. If I read the same article twice, that would count as 2 views because it shows its an interesting enough article to read it more than once.

**Comment by mahmoudal99** [comment]
I think using article ids is the better solution and simpler like you said but would you not store the list of liked article of a user in the database rather than local storage?

**Comment by salahusama** [comment]
> I think using article ids is the better solution and simpler like you said but would you not store the list of liked article of a user in the database rather than local storage?

Yeah, that might work, but we won't have user IDs since we don't have log in. If we assign machine IDs, then we can store that in the DB, but if they clear cache or local storage, they'd be assigned a new ID and the one in the DB won't be used, but still won't be deleted.

If we just store it in local storage, and they clear it, it's the same functionality but we won't have to deal with outdated IDs in the DB.

**Comment by salahusama** [comment]
For views:
* After an article loads (`ArticleView` page), update its view count
  * We could possible add a timer to wait 5 seconds before updating to make sure it wasn't an accidental click - but naa

For Likes:
* Just have a button users can click and update the like count for that article
* Later on we might store a list of article ids in `localStorage` to show that they already liked this article. We can't unlike though at the moment so maybe not anyway

**Comment by salahusama** [comment]
I'll separate this into 2 issues as the view count is quite easier. Will leave this issue for the likes. The new issue (mai-youth/website-fe#59) for the views.

**Comment by salahusama** [comment]
Something like these action buttons from [here](https://www.helpscout.com/blog/introducing-messages/) for likes would be nice. At the start it could just be one button to like, but we can add more to share later.

![image.png](https://images.zenhubusercontent.com/5bf2e6a95e53e9795dc31c2b/f1430b71-4263-457b-8845-988c350da97c)
